name: 'Setup Open Watcom'
description: 'Setup an Open Watcom environment'
branding:
  color: yellow
  icon: download-cload
inputs:
  version:
    description: 'Open Watcom version: choices = [1.8, 1.9, 2.0, 2.0-64]'
    required: false
    default: '2.0'
  tag:
    description: 'Tag of snapshot to use: current, last or date. (only used for 2.0)'
    required: false
    default: null
  location:
    description: 'Location where Open Watcom should be extracted to (default=/opt/watcom or C:\\watcom)'
    required: false
    default: null
  environment:
    description: 'Set environment variables (WATCOM + PATH)'
    required: false
    default: true
runs:
  using: 'node16'
  main: 'index.js'
