name: 'Setup Open Watcom'
description: 'Setup an Open Watcom environment'
branding:
  color: yellow
  icon: download-cloud
inputs:
  version:
    description: 'Open Watcom version: choices = [1.8, 1.9, 2.0, 2.0-64]'
    required: false
    default: '2.0'
  tag:
    description: 'Tag of snapshot to use: current, last or date. (only used for 2.0)'
    required: false
    default: ''
  location:
    description: 'Location where Open Watcom should be extracted to (default=$HOME/watcom or %USERPROFILE%\\WATCOM)'
    required: false
    default: ''
  environment:
    description: 'Set default Open Watcom environment variables (WATCOM + INCLUDE + PATH)'
    required: false
    default: true
  target:
    description: 'Set target OS (one of values "", "dos", "win", "nt", "os2", "os2-16", "linux"), change header search path (INCLUDE)'
    required: false
    default: ''
runs:
  using: 'node20'
  main: 'index.js'
